import * as Phaser from 'phaser';
// Note: import * as Phaser is required — Phaser's dist build has no default export
import { canPlaceRoom } from '../../simulation/rooms';
import { drawFoodStockpile, drawOreStockpile, drawWoodStockpile, drawTerrain, drawOverlay, drawAgents, drawOffScreenIndicator } from './WorldRender';
import { gameTick } from './WorldTick';
import { createWarmthField, createDangerField } from '../../simulation/diffusion';
import { TICK_RATE_MS, TILE_SIZE } from '../../shared/constants';
import { type OverlayMode, type Tile, type Goblin, type Adventurer, type ColonyGoal, type FoodStockpile, type OreStockpile, type WoodStockpile, type LogEntry, type Chapter, type Room, type RoomType } from '../../shared/types';
import { updateCamera } from './WorldCamera';
import { emitGameState } from './WorldState';
import * as WorldGoals from './WorldGoals';
import { bus } from '../../shared/events';
import { type Weather } from '../../simulation/weather';
import { SPRITE_CONFIG } from '../tileConfig';

import { initializeWorld } from './WorldInit';

export class WorldScene extends Phaser.Scene {
  public grid: Tile[][] = [];
  public goblins: Goblin[] = [];
  public tick = 0;
  public selectedGoblinId: string | null = null;
  public terrainDirty = true;
  public lastTickTime = 0;
  public paused = false;
  public speedMultiplier = 1;
  public readonly SPEED_STEPS = [0.25, 0.5, 1, 2, 4];

  // Active player command tile (shown as flag)
  public commandTile: { x: number; y: number } | null = null;

  // Tilemap for terrain
  public map!: Phaser.Tilemaps.Tilemap;
  public floorLayer!: Phaser.Tilemaps.TilemapLayer;
  public objectLayer!: Phaser.Tilemaps.TilemapLayer;

  // Graphics layers
  public selectionGfx!: Phaser.GameObjects.Graphics;
  public flagGfx!: Phaser.GameObjects.Graphics;
  public ambientGfx!: Phaser.GameObjects.Graphics;
  public overlayGfx!: Phaser.GameObjects.Graphics;
  public overlayMode: OverlayMode = 'off';

  // One sprite per living goblin
  public goblinSprites = new Map<string, Phaser.GameObjects.Sprite>();
  // Persistent grave sprites for dead goblins (red, flipped upside-down)
  public goblinGhostSprites = new Map<string, Phaser.GameObjects.Sprite>();
  // Off-screen arrow indicator for selected goblin
  public offScreenGfx!: Phaser.GameObjects.Graphics;
  // Adventurer raid state
  public adventurers: Adventurer[] = [];
  public adventurerSprites = new Map<string, Phaser.GameObjects.Sprite>();

  // Succession state
  public spawnZone!: { x: number; y: number; w: number; h: number };
  public pendingSuccessions: { deadGoblinId: string; spawnAtTick: number }[] = [];

  // Weather system — affects growback rates and goblin metabolism
  public weather!: Weather;

  // Diffusion fields — recomputed every tick, never saved
  public warmthField = createWarmthField();
  public dangerField = createDangerField();
  public dangerFieldPrev = createDangerField(); // double-buffer for decay

  // Event log noise reduction
  public combatHits = new Map<string, number>();  // goblin id → hit count this encounter

  // Colony goal + food/ore/wood stockpiles (expand as each fills up)
  public colonyGoal!: ColonyGoal;
  public goalStartTick = 0;
  public adventurerKillCount = 0;
  public foodStockpiles: FoodStockpile[] = [];
  public oreStockpiles: OreStockpile[] = [];
  public woodStockpiles: WoodStockpile[] = [];
  public foodStockpileGfxList: Phaser.GameObjects.Graphics[] = [];
  public foodStockpileImgList: Phaser.GameObjects.Image[] = [];
  public oreStockpileGfxList: Phaser.GameObjects.Graphics[] = [];
  public oreStockpileImgList: Phaser.GameObjects.Image[] = [];
  public woodStockpileGfxList: Phaser.GameObjects.Graphics[] = [];
  public woodStockpileImgList: Phaser.GameObjects.Image[] = [];

  // Event log history (persisted to save, restored on load)
  public logHistory: LogEntry[] = [];
  // Chronicle chapters — generated by storyteller AI on goal completion
  public chapters: Chapter[] = [];
  public lastChapterTick = 0;
  // World seed — stored for save/load and display
  public worldSeed = '';

  // Player-placed rooms
  public rooms: Room[] = [];

  // Build mode state
  public buildMode: RoomType | null = null;
  public buildPreview: { x: number; y: number } | null = null;
  public buildPreviewGfx!: Phaser.GameObjects.Graphics;

  // WASD keys (null when keyboard unavailable on touch devices)
  public wasd: {
    W: Phaser.Input.Keyboard.Key;
    A: Phaser.Input.Keyboard.Key;
    S: Phaser.Input.Keyboard.Key;
    D: Phaser.Input.Keyboard.Key;
  } | null = null;

  // Touch input state
  public isTouchDevice = false;
  public longPressTimer: ReturnType<typeof setTimeout> | null = null;
  public longPressFired = false;
  public minZoom = 0.6;

  constructor() {
    super({ key: 'WorldScene' });
  }

  public static makeGoal(type: ColonyGoal['type'], generation: number): ColonyGoal {
    return WorldGoals.makeGoal(type, generation);
  }

  create() {
    initializeWorld(this);
  }

  // ── Simulation tick ────────────────────────────────────────────────────


  /** Send commandTarget to selected goblin (or all if none selected). */
  public applyCommand(tx: number, ty: number) {
    const targets = this.selectedGoblinId
      ? this.goblins.filter(d => d.alive && d.id === this.selectedGoblinId)
      : this.goblins.filter(d => d.alive);

    for (const d of targets) {
      d.commandTarget = { x: tx, y: ty };
    }

    const who = this.selectedGoblinId
      ? (this.goblins.find(d => d.id === this.selectedGoblinId)?.name ?? '?')
      : `${targets.length} goblins`;

    bus.emit('logEntry', {
      tick: this.tick,
      goblinId: this.selectedGoblinId ?? 'all',
      goblinName: who,
      message: `ordered to(${tx}, ${ty})`,
      level: 'info',
    });
  }


  /** Place a room at the current build preview location. */
  public placeRoom() {
    if (!this.buildMode || !this.buildPreview) return;
    const { x, y } = this.buildPreview;
    const w = 5, h = 5;
    if (!canPlaceRoom(this.grid, this.rooms, x, y, w, h)) return;

    const room: Room = {
      id: `room - ${Date.now()} `,
      type: this.buildMode,
      x, y, w, h,
    };
    this.rooms.push(room);

    bus.emit('logEntry', {
      tick: this.tick,
      goblinId: 'world',
      goblinName: 'COLONY',
      message: `Storage zone designated at(${x}, ${y})!`,
      level: 'info',
    });

    this.terrainDirty = true;
  }

  // ── Simulation tick ────────────────────────────────────────────────────


  public togglePause() {
    this.paused = !this.paused;
    emitGameState(this);
  }

  public adjustSpeed(dir: 1 | -1) {
    const i = this.SPEED_STEPS.indexOf(this.speedMultiplier);
    const next = i + dir;
    if (next >= 0 && next < this.SPEED_STEPS.length) {
      this.speedMultiplier = this.SPEED_STEPS[next];
      emitGameState(this);
    }
  }

  public cycleSelected(direction: 1 | -1) {
    const alive = this.goblins.filter(d => d.alive);
    if (alive.length === 0) return;
    const currentIdx = alive.findIndex(d => d.id === this.selectedGoblinId);
    const nextIdx = ((currentIdx + direction) + alive.length) % alive.length;
    this.selectedGoblinId = alive[nextIdx].id;
    emitGameState(this);
  }

  // ── Colony goal ────────────────────────────────────────────────────────

  /** Create Phaser graphics + sprite objects for a newly added food stockpile. */
  public addFoodStockpileGraphics(stockpile: FoodStockpile): void {
    const cx = stockpile.x * TILE_SIZE + TILE_SIZE / 2;
    const cy = stockpile.y * TILE_SIZE + TILE_SIZE / 2;
    this.foodStockpileImgList.push(this.add.image(cx, cy, 'tiles', SPRITE_CONFIG.foodStockpile).setDepth(3));
    this.foodStockpileGfxList.push(this.add.graphics().setDepth(3));
  }

  /** Create Phaser graphics + sprite objects for a newly added ore stockpile. */
  public addOreStockpileGraphics(stockpile: OreStockpile): void {
    const cx = stockpile.x * TILE_SIZE + TILE_SIZE / 2;
    const cy = stockpile.y * TILE_SIZE + TILE_SIZE / 2;
    this.oreStockpileImgList.push(this.add.image(cx, cy, 'tiles', SPRITE_CONFIG.oreStockpile).setDepth(3));
    this.oreStockpileGfxList.push(this.add.graphics().setDepth(3));
  }

  /** Create Phaser graphics + sprite objects for a newly added wood stockpile. */
  public addWoodStockpileGraphics(stockpile: WoodStockpile): void {
    const cx = stockpile.x * TILE_SIZE + TILE_SIZE / 2;
    const cy = stockpile.y * TILE_SIZE + TILE_SIZE / 2;
    this.woodStockpileImgList.push(this.add.image(cx, cy, 'tiles', SPRITE_CONFIG.woodStockpile).setDepth(3));
    this.woodStockpileGfxList.push(this.add.graphics().setDepth(3));
  }



  // ── Main loop ──────────────────────────────────────────────────────────

  update(time: number, delta: number) {
    updateCamera(this, delta);

    // Simulation tick — skipped when paused; interval shrinks at higher speeds
    if (!this.paused && time - this.lastTickTime >= TICK_RATE_MS / this.speedMultiplier) {
      this.lastTickTime = time;
      gameTick(this);
    }

    if (this.terrainDirty || !this.paused) {
      if (this.terrainDirty) drawTerrain(this);
      drawOverlay(this); // refresh density + ambient glow
    }
    drawAgents(this);
    drawFoodStockpile(this);
    drawOreStockpile(this);
    drawWoodStockpile(this);
    drawOffScreenIndicator(this);
  }
}
