/**
 * Event bus (mitt) — decouples game/simulation from UI. Game loop and sim emit; React HUD and
 * Phaser subscribe. See the Events type below for payloads.
 *
 * Adding a new event: add name and payload to Events, emit with bus.emit('eventName', payload),
 * subscribe with bus.on('eventName', handler). Keep payloads plain data (no class instances).
 */

import mitt from 'mitt';
import type { GameState, LogEntry, TileInfo, MiniMapData, Adventurer, OverlayMode, Chapter, RoomType } from './types';
import type { WorkCategoryId } from '../simulation/workerTargets';

type Events = {
  gameState:      GameState;
  logEntry:       LogEntry;
  clearLog:       undefined;
  restoreLog:     LogEntry[];
  settingsChange: { llmEnabled?: boolean; llmProvider?: 'anthropic' | 'groq' };
  tileHover:      TileInfo | null;
  miniMapUpdate:  MiniMapData;
  controlChange:  { action: 'pause' | 'speedUp' | 'speedDown' | 'newColony' };
  stockpileSelect: { kind: 'food' | 'ore' | 'wood' | 'meal' | 'plank' | 'bar'; idx: number } | null;
  hearthSelect: { x: number; y: number } | null;
  adventurerSelect:    Adventurer | null;
  tokenUsage:      { inputTotal: number; outputTotal: number; callCount: number; lastInput: number; lastOutput: number };
  /** Mobile on-screen button: cycle overlay mode */
  overlayChange:  { mode: OverlayMode };
  /** Mobile on-screen button: cycle selected goblin */
  cycleSelected:  { direction: 1 | -1 };
  /** A new chapter was generated by the storyteller AI. */
  chronicleChapter: Chapter;
  /** Restore all chapters from save data (on load). */
  restoreChronicle: Chapter[];
  /** Show chronicle modal (pause world until dismissed). */
  chronicleModal: { open: boolean; chapter: Chapter; allChapters: Chapter[] };
  /** Player dismissed the chronicle modal; resume simulation. */
  chronicleModalClosed: undefined;
  /** Player enters/exits build mode for room placement. */
  buildMode: { roomType: RoomType } | null;
  /** A batch of meals was cooked. */
  mealsCooked: number;
  /** Worker target change from planning panel. */
  workerTargetChange: { category: WorkCategoryId; value: number };
  /** Player-assigned job for a goblin (from goblin HUD). */
  goblinAssignedJob: { goblinId: string; job: WorkCategoryId | null };
  /** Dev: ambient glow debug sliders changed — refresh overlay + blend mode. */
  ambientGlowDebugChanged: undefined;
};

export const bus = mitt<Events>();
