import mitt from 'mitt';
import type { GameState, LogEntry, TileInfo, MiniMapData, Goblin, OverlayMode, Chapter } from './types';

type Events = {
  gameState:      GameState;
  logEntry:       LogEntry;
  clearLog:       undefined;
  restoreLog:     LogEntry[];
  settingsChange: { llmEnabled?: boolean; llmProvider?: 'anthropic' | 'groq' };
  tileHover:      TileInfo | null;
  miniMapUpdate:  MiniMapData;
  controlChange:  { action: 'pause' | 'speedUp' | 'speedDown' | 'newColony' };
  stockpileSelect: { kind: 'food' | 'ore' | 'wood'; idx: number } | null;
  goblinSelect:    Goblin | null;
  tokenUsage:      { inputTotal: number; outputTotal: number; callCount: number; lastInput: number; lastOutput: number };
  /** Mobile on-screen button: cycle overlay mode */
  overlayChange:  { mode: OverlayMode };
  /** Mobile on-screen button: cycle selected dwarf */
  cycleSelected:  { direction: 1 | -1 };
  /** A new chapter was generated by the storyteller AI. */
  chronicleChapter: Chapter;
  /** Restore all chapters from save data (on load). */
  restoreChronicle: Chapter[];
};

export const bus = mitt<Events>();
