/**
 * Event bus (mitt) — decouples game/simulation from UI. Game loop and sim emit; React HUD and
 * Phaser subscribe. See the Events type below for payloads.
 *
 * Adding a new event: add name and payload to Events, emit with bus.emit('eventName', payload),
 * subscribe with bus.on('eventName', handler). Keep payloads plain data (no class instances).
 */

import mitt from 'mitt';
import type { GameState, LogEntry, TileInfo, MiniMapData, Adventurer, OverlayMode, Chapter, RoomType } from './types';

type Events = {
  gameState:      GameState;
  logEntry:       LogEntry;
  clearLog:       undefined;
  restoreLog:     LogEntry[];
  settingsChange: { llmEnabled?: boolean; llmProvider?: 'anthropic' | 'groq' };
  tileHover:      TileInfo | null;
  miniMapUpdate:  MiniMapData;
  controlChange:  { action: 'pause' | 'speedUp' | 'speedDown' | 'newColony' };
  stockpileSelect: { kind: 'food' | 'ore' | 'wood' | 'meal'; idx: number } | null;
  adventurerSelect:    Adventurer | null;
  tokenUsage:      { inputTotal: number; outputTotal: number; callCount: number; lastInput: number; lastOutput: number };
  /** Mobile on-screen button: cycle overlay mode */
  overlayChange:  { mode: OverlayMode };
  /** Mobile on-screen button: cycle selected goblin */
  cycleSelected:  { direction: 1 | -1 };
  /** A new chapter was generated by the storyteller AI. */
  chronicleChapter: Chapter;
  /** Restore all chapters from save data (on load). */
  restoreChronicle: Chapter[];
  /** Player enters/exits build mode for room placement. */
  buildMode: { roomType: RoomType } | null;
  /** A batch of meals was cooked. */
  mealsCooked: number;
};

export const bus = mitt<Events>();
